### ISSUE TITLE
PIN is always wrong 

### ISSUE THREAD

**Issue by Stooovie** [neffs/ha-cometblue#1]
Can’t get it to work even with the HACS component (I removed the original one beforehand). I do have the entity in the UI, but it’s Unavailable and I’m getting “can’t read the data, is your PIN correct?”

The PIN always works with the Europrog iPhone apps just fine. 

I’ve tried

- changing PIN via Europrog app
- disabling BT on iPhone
- changing PIN to 6-digit new PIN
- removing batteries to reset the pin to 000000

I did change the config yaml and restarted HA each time. 

Mac address is correct, the entity wouldn’t work at all with wrong addres. 

HA 0.100.3 on RPI 4 with the built-in BT hardware.

**Comment by Stooovie** [comment]
Here's the full trace

`climate.thermostat1 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/cometblue/climate.py", line 182, in update
    self._thermostat.update()
  File "/config/custom_components/cometblue/climate.py", line 243, in update
    self.connect()
  File "/config/custom_components/cometblue/climate.py", line 214, in connect
    self._conn.writeCharacteristic(PASSWORD_HANDLE, struct.pack(_PIN_STRUCT_PACKING, self._pin), withResponse=True)
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 543, in writeCharacteristic
    return self._getResp('wr')
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 368, in _waitResp
    raise BTLEGattError("Bluetooth command failed", resp)
bluepy.btle.BTLEGattError: Bluetooth command failed (code: 3, error: Attribute can't be written)`

**Comment by neffs** [comment]
should be fixed in 2fa6475638e0030531e0b71c567ad8cee3861bb6 and https://github.com/neffs/python-cometblue_lite/commit/a99642af26778e8adec8e26ddb2e669633097804
