### ISSUE TITLE
Connection issue with newer Sygonix Thermostat

### ISSUE THREAD

**Issue by bennibeloisi** [neffs/ha-cometblue#4]
I am really thankful for your work on this add on for HA, loving it really,
im using 2 older Sygonix Thermostat (old Firmeware, external Bluetooth board on the thermostat, aka using the old handles) and 2 newer thermostats with integrated Bluetooth that is using the new handles.

The two old ones are working perfectly, instant response, always update, no problem at all.
The newer ones are however not working as intended. They display the correct value, but as soon as i try to set a new target temp the thermostat in HA goes to -64° C and will only show the proper termperature after the next update cycle. not a big deal, but some times the thermostat does not update at all. E.g. when i use the thermostat on the Lovelace UI it wont do anything, only if i open the entity and set the temperature manually with the up and down arrows. unfortunately with automations it also only works 50% of the time. 

The new ones work quite ok with the add on from https://github.com/floxdeveloper/ha-cometblue which is based on your previous code. it however does miss features such as battery level.

Here is the error log i get. 
if you have time i'd really appreciate you taking a look into this as i would like to get some more the thermostats for the other heaters i have. 

```
Logger: homeassistant.helpers.entity
Source: custom_components/cometblue/climate.py:175
First occured: 8:17:09 PM (19 occurences)
Last logged: 8:35:09 PM

Update for climate.thermostatbed fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cometblue_lite/cometblue.py", line 274, in update
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/cometblue_lite/cometblue.py", line 196, in connect
    self._conn.connect(self._address)
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 433, in _connect
    self._writeCmd("conn %s %s\n" % (addr, addrType))
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 305, in _writeCmd
    self._helper.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/cometblue/climate.py", line 175, in update
    self._thermostat.update()
  File "/usr/local/lib/python3.7/site-packages/cometblue_lite/cometblue.py", line 304, in update
    self.disconnect()
  File "/usr/local/lib/python3.7/site-packages/cometblue_lite/cometblue.py", line 226, in disconnect
    self._conn.disconnect()
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 453, in disconnect
    self._writeCmd("disc\n")
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 305, in _writeCmd
    self._helper.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

```

**Comment by neffs** [comment]
It looks like the connection was closed by the bluetooth stack. Do you use hassio?

Could you add this to your configuration.yaml to get more debug information?

```
logger:
  default: error
  logs:
    custom_components.cometblue: debug
    cometblue_lite: debug
```

**Comment by bennibeloisi** [comment]
Thank you for your quick answer!
yes, i'm on hassio.
Here is what the log says: 

```
2020-03-21 17:24:59 INFO (SyncWorker_4) [custom_components.cometblue.climate] Updating status for 98:07:9A:C8:27:F9
2020-03-21 17:24:59 DEBUG (SyncWorker_4) [cometblue_lite.cometblue] Connecting to device 98:07:9A:C8:27:F9
2020-03-21 17:25:04 DEBUG (SyncWorker_4) [cometblue_lite.cometblue] Unable to connect to the device 98:07:9A:C8:27:F9, retrying.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cometblue_lite/cometblue.py", line 196, in connect
    self._conn.connect(self._address)
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 445, in connect
    self._connect(addr, addrType, iface)
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 98:07:9A:C8:27:F9, addr type: public
2020-03-21 17:25:08 DEBUG (SyncWorker_4) [cometblue_lite.cometblue] Discovering characteristics 98:07:9A:C8:27:F9
2020-03-21 17:25:11 DEBUG (SyncWorker_4) [cometblue_lite.cometblue] Disconnected from device 98:07:9A:C8:27:F9
2020-03-21 17:25:27 DEBUG (SyncWorker_18) [custom_components.cometblue.climate] Temperature to set: 27.0
2020-03-21 17:25:27 INFO (SyncWorker_9) [custom_components.cometblue.climate] Updating status for 98:07:9A:C8:27:F9
2020-03-21 17:25:27 DEBUG (SyncWorker_9) [cometblue_lite.cometblue] Connecting to device 98:07:9A:C8:27:F9
2020-03-21 17:25:30 DEBUG (SyncWorker_9) [cometblue_lite.cometblue] Updating Temperatures to target_temp={54}
2020-03-21 17:25:30 DEBUG (SyncWorker_9) [cometblue_lite.cometblue] Disconnected from device 98:07:9A:C8:27:F9
```
here is a picture of how it looks in the UI. 
[https://photos.app.goo.gl/6AYjynjMojk1x79k9](https://photos.app.goo.gl/6AYjynjMojk1x79k9)

Thank you

**Comment by fleXible** [comment]
I'm having the same issue with my Comet Blue devices and did some debugging. I couldn't pinpoint the cause exactly, but I believe it is a bug in the way the `bluepy` library is handling the opening and closing of the communication to the bluetooth stack. A small helper tool in `C` is used, which sometimes is terminated already, when `bluepy` tries to close the connection down.

Still testing different approaches to mitigate the behaviour, but haven't yet found one, I'm happy with.

**Comment by fleXible** [comment]
I've been running those changes for the last several weeks and haven't had any serious  connection problems ever since.

**Comment by bennibeloisi** [comment]
Thank you both a lot, I updated yesterday and tried it a few times without any temperature drops when adjusting the thermostats.
